
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LIST_FOOD_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_FOOD_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FOOD_FAIL = 'PRODUCT_LIST_FAIL';

export const ALLPRODUCT_LIST_REQUEST = 'ALLPRODUCT_LIST_REQUEST';
export const ALLPRODUCT_LIST_SUCCESS = 'ALLPRODUCT_LIST_SUCCESS';
export const ALLPRODUCT_LIST_FAIL = 'ALLPRODUCT_LIST_FAIL';


export const FEATUREDPRODUCT_LIST_REQUEST = 'FEATUREDPRODUCT_LIST_REQUEST';
export const FEATUREDPRODUCT_LIST_SUCCESS = 'FEATUREDPRODUCT_LIST_SUCCESS';
export const FEATUREDPRODUCT_LIST_FAIL = 'FEATUREDPRODUCT_LIST_FAIL';

export const RELATEDPRODUCT_LIST_REQUEST = 'RELATEDPRODUCT_LIST_REQUEST';
export const RELATEDPRODUCT_LIST_SUCCESS = 'RELATEDPRODUCT_LIST_SUCCESS';
export const RELATEDPRODUCT_LIST_FAIL = 'RELATEDPRODUCT_LIST_FAIL';

export const CATEGORYONEPRODUCT_LIST_REQUEST = 'CATEGORYONEPRODUCT_LIST_REQUEST';
export const CATEGORYONEPRODUCT_LIST_SUCCESS = 'CATEGORYONEPRODUCT_LIST_SUCCESS';
export const CATEGORYONEPRODUCT_LIST_FAIL = 'CATEGORYONEPRODUCT_LIST_FAIL';

export const CATEGORYTWOPRODUCT_LIST_REQUEST = 'CATEGORYTWOPRODUCT_LIST_REQUEST';
export const CATEGORYTWOPRODUCT_LIST_SUCCESS = 'CATEGORYTWOPRODUCT_LIST_SUCCESS';
export const CATEGORYTWOPRODUCT_LIST_FAIL = 'CATEGORYTWOPRODUCT_LIST_FAIL';

export const CATEGORYTHREEPRODUCT_LIST_REQUEST = 'CATEGORYTHREEPRODUCT_LIST_REQUEST';
export const CATEGORYTHREEPRODUCT_LIST_SUCCESS = 'CATEGORYTHREEPRODUCT_LIST_SUCCESS';
export const CATEGORYTHREEPRODUCT_LIST_FAIL = 'CATEGORYTHREEPRODUCT_LIST_FAIL';

export const CATEGORYFOURPRODUCT_LIST_REQUEST = 'CATEGORYFOURPRODUCT_LIST_REQUEST';
export const CATEGORYFOURPRODUCT_LIST_SUCCESS = 'CATEGORYFOURPRODUCT_LIST_SUCCESS';
export const CATEGORYFOURPRODUCT_LIST_FAIL = 'CATEGORYFOURPRODUCT_LIST_FAIL';

export const RELATEDBRAND_LIST_REQUEST = 'RELATEDBRAND_LIST_REQUEST';
export const RELATEDBRAND_LIST_SUCCESS = 'RELATEDBRAND_LIST_SUCCESS';
export const RELATEDBRAND_LIST_FAIL = 'RELATEDBRAND_LIST_FAIL';


export const SIMILARPRODUCT_LIST_REQUEST = 'SIMILARPRODUCT_LIST_REQUEST';
export const SIMILARPRODUCT_LIST_SUCCESS = 'SIMILARPRODUCT_LIST_SUCCESS';
export const SIMILARPRODUCT_LIST_FAIL = 'SIMILARPRODUCT_LIST_FAIL';


export const MOSTVIEWEDPRODUCT_LIST_REQUEST = 'MOSTVIEWEDPRODUCT_LIST_REQUEST';
export const MOSTVIEWEDPRODUCT_LIST_SUCCESS = 'MOSTVIEWEDPRODUCT_LIST_SUCCESS';
export const MOSTVIEWEDPRODUCT_LIST_FAIL = 'MOSTVIEWEDPRODUCT_LIST_FAIL';


export const  LATESTPRODUCT_LIST_REQUEST = 'LATESTPRODUCT_LIST_REQUEST';
export const LATESTPRODUCT_LIST_SUCCESS = 'LATESTPRODUCT_LIST_SUCCESS';
export const LATESTPRODUCT_LIST_FAIL = 'LATESTPRODUCT_LIST_FAIL';

export const  RATING_LIST_REQUEST = 'RATING_LIST_REQUEST';
export const RATING_LIST_SUCCESS = 'RATING_LIST_SUCCESS';
export const RATING_LIST_FAIL = 'RATING_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const  FOOD_LATESTPRODUCT_LIST_REQUEST = 'FOOD_LATESTPRODUCT_LIST_REQUEST';
export const FOOD_LATESTPRODUCT_LIST_SUCCESS = 'FOOD_LATESTPRODUCT_LIST_SUCCESS';
export const FOOD_LATESTPRODUCT_LIST_FAIL = 'FOOD_LATESTPRODUCT_LIST_FAIL';


export const FOOD_ALLPRODUCT_LIST_REQUEST = 'FOOD_ALLPRODUCT_LIST_REQUEST';
export const FOOD_ALLPRODUCT_LIST_SUCCESS = 'FOOD_ALLPRODUCT_LIST_SUCCESS';
export const FOOD_ALLPRODUCT_LIST_FAIL = 'FOOD_ALLPRODUCT_LIST_FAIL';


export const FOOD_FEATUREDPRODUCT_LIST_REQUEST = 'FOOD_FEATUREDPRODUCT_LIST_REQUEST';
export const FOOD_FEATUREDPRODUCT_LIST_SUCCESS = 'FOOD_FEATUREDPRODUCT_LIST_SUCCESS';
export const FOOD_FEATUREDPRODUCT_LIST_FAIL = 'FOOD_FEATUREDPRODUCT_LIST_FAIL';


export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';


export const PRODUCT_CATEGORY_LIST_FOOD_REQUEST = 'PRODUCT_CATEGORY_LIST_FOOD_REQUEST';
export const PRODUCT_CATEGORY_LIST_FOOD_SUCCESS = 'PRODUCT_CATEGORY_LIST_FOOD_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FOOD_FAIL = 'PRODUCT_CATEGORY_LIST_FOOD_FAIL';

export const PRODUCT_REVIEW_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_REVIEW_LIST_SUCCESS = 'PRODUCT_REVIEW_LIST_SUCCESS';
export const PRODUCT_REVIEW_LIST_FAIL = 'PRODUCT_REVIEW_LIST_FAIL';

export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';



